#ifndef ADIOS2_BINDINGS_CXX11_CXX11_ADIOSVIEW_H_
#define ADIOS2_BINDINGS_CXX11_CXX11_ADIOSVIEW_H_

namespace adios2
{
template <class T>
class AdiosView;
}

#endif /* ADIOS2_BINDINGS_CXX11_CXX11_ADIOSVIEW_H_ */
