sudo: false
language: cpp
dist: trusty
addons:
  apt:
    packages:
      - clang-3.8
      - clang-format-3.8
      - clang-tidy-3.8
      - libmpich-dev
before_install:
  - pushd ${HOME}
  - wget http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - wget http://www.cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz
  - popd
install:
  - pushd ${HOME}
  - tar -xf clang+llvm-6.0.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
  - tar -xf cmake-3.7.2-Linux-x86_64.tar.gz
  - export PATH="${PWD}/cmake-3.7.2-Linux-x86_64/bin:${PATH}"
  - popd
  - pip install --user flake8
  - git lfs install --skip-smudge
  - git config --global clangformat.binary clang-format-3.8
  - ./scripts/travis/build-cppcheck.sh
env:
  matrix:
    - BUILD_MATRIX_ENTRY=format
    - BUILD_MATRIX_ENTRY=analyze
    - BUILD_MATRIX_ENTRY=check
script:
  - git lfs pull
  - git reset --hard ${TRAVIS_PULL_REQUEST_SHA}
  - ${TRAVIS_BUILD_DIR}/scripts/travis/run.sh
