sudo: false
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages: clang-format-3.8
      install:
        - pip install --user flake8
        - git config --global clangformat.binary clang-format-3.8
      env: BUILD_MATRIX_ENTRY=format

#    - os: linux
#      dist: trusty
#      addons:
#        apt:
#          sources: [ubuntu-toolchain-r-test, llvm-toolchain-trusty-6.0]
#          packages: clang-6.0
#      env: BUILD_MATRIX_ENTRY=analyze

#    - os: linux
#      dist: trusty
#      addons:
#        apt:
#          sources: ubuntu-toolchain-r-test
#          packages: cppcheck
#      env: BUILD_MATRIX_ENTRY=check

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages: [ gfortran hdf5-tools libhdf5-dev libzmq3-dev python-numpy]
      env: GENERATOR=make BUILD_MATRIX_ENTRY=build

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          packages: [ gfortran openmpi-bin libopenmpi-dev libhdf5-openmpi-dev libzmq3-dev python-numpy python-mpi4py ]
      env: GENERATOR=make BUILD_MATRIX_ENTRY=build MPI=openmpi

    - os: osx
      osx_image: xcode8
      compiler: clang
      before_install:
        - defaults write com.apple.dt.Xcode IDEBuildingContinueBuildingAfterErrors 1
        - brew update
        - rm -f /usr/local/include/c++
        - brew install zeromq
      env: GENERATOR=xcode BUILD_MATRIX_ENTRY=build

    - os: osx
      osx_image: xcode8
      compiler: clang
      before_install:
        - defaults write com.apple.dt.Xcode IDEBuildingContinueBuildingAfterErrors 1
        - brew update
        - rm -f /usr/local/include/c++
        - brew install zeromq openmpi libfabric
        - brew install hdf5 --with-mpi
      env: GENERATOR=xcode BUILD_MATRIX_ENTRY=build MPI=openmpi

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      before_install:
        - defaults write com.apple.Xcode PBXBuildsContinueAfterErrors YES
        - brew update
        - rm -f /usr/local/include/c++
        - brew install zeromq hdf5
      env: GENERATOR=xcode BUILD_MATRIX_ENTRY=build

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      before_install:
        - defaults write com.apple.Xcode PBXBuildsContinueAfterErrors YES
        - brew update
        - rm -f /usr/local/include/c++
        - brew install zeromq openmpi libfabric
        - brew install hdf5 --with-mpi
      env: GENERATOR=xcode BUILD_MATRIX_ENTRY=build MPI=openmpi

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      before_install:
        - defaults write com.apple.Xcode PBXBuildsContinueAfterErrors YES
        - brew update
        - rm -f /usr/local/include/c++
        - brew install zeromq hdf5 
      env: GENERATOR=xcode BUILD_MATRIX_ENTRY=build

    - os: osx
      osx_image: xcode9.3
      compiler: clang
      before_install:
        - defaults write com.apple.Xcode PBXBuildsContinueAfterErrors YES
        - brew update
        - rm -f /usr/local/include/c++
        - brew install zeromq openmpi libfabric
        - brew install hdf5 --with-mpi
      env: GENERATOR=xcode BUILD_MATRIX_ENTRY=build MPI=openmpi

script:
  - git reset --hard ${TRAVIS_PULL_REQUEST_SHA}
  - ${TRAVIS_BUILD_DIR}/scripts/travis/run.sh
