version: 1.0.{build}

skip_branch_with_pr: true

os:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64

install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps

  ############################################################################
  # Install Ninja
  ############################################################################
  - set NINJA_URL="https://github.com/Kitware/ninja/releases/download/v1.8.2.g972a7.kitware.dyndep-1/ninja-1.8.2.g972a7.kitware.dyndep-1_i686-pc-windows-msvc.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z e ninja.zip -oC:\projects\deps\ninja > nul
  - set PATH=C:\projects\deps\ninja;%PATH%
  - ninja --version

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - set CMAKE_URL="https://cmake.org/files/v3.15/cmake-3.15.3-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

#   ### Having trouble with enabling python on windows
#   - set PATH=C:\Python27-x64;C:\Python27-x64\Scripts;%PATH%
#   - "python.exe -m pip install numpy"

# init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_build:
#- del /q /f "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
- cd C:\projects\adios2
- git reset --hard %APPVEYOR_PULL_REQUEST_HEAD_COMMIT%
- ps: |
    if(Test-Path env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH) {
        $env:BUILD_NAME_BRANCH = $env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH
        $env:CUSTOM_BUILD_NAME = ("pr{0}_{1}_{2}_vs{3}" -f $env:APPVEYOR_PULL_REQUEST_NUMBER, $env:BUILD_NAME_BRANCH, $env:APPVEYOR_BUILD_NUMBER, $env:APPVEYOR_BUILD_WORKER_IMAGE.split()[2] )
    } else {
        $env:BUILD_NAME_BRANCH = $env:APPVEYOR_REPO_BRANCH
        $env:CUSTOM_BUILD_NAME = ("{0}_{1}_vs{2}" -f $env:BUILD_NAME_BRANCH, $env:APPVEYOR_BUILD_NUMBER, $env:APPVEYOR_BUILD_WORKER_IMAGE.split()[2] )
    }
    if($env:APPVEYOR_BUILD_WORKER_IMAGE.split()[2] -eq "2015") {
        $env:VCVARSALLPATH = 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
        $env:VCVARSALLARGS = "amd64"
    } elseif($env:APPVEYOR_BUILD_WORKER_IMAGE.split()[2] -eq "2017") {
        $env:VCVARSALLPATH = 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat'
        $env:VCVARSALLARGS = "amd64"
    }
    $env:CC = "cl.exe"
    $env:CXX = "cl.exe"
- call "%VCVARSALLPATH%" %VCVARSALLARGS%
- ctest.exe -VV -S ..\adios2\scripts\appveyor\appveyor_ninja.cmake
    -Ddashboard_full=OFF
    -Ddashboard_do_update=true
    -DCTEST_BUILD_NAME=%CUSTOM_BUILD_NAME%

build_script:
- ctest.exe -VV -S ..\adios2\scripts\appveyor\appveyor_ninja.cmake
    -Ddashboard_full=OFF
    -Ddashboard_do_configure=true
    -Ddashboard_do_build=true
    -DCTEST_BUILD_NAME=%CUSTOM_BUILD_NAME%

test_script:
- ctest.exe -VV -S ..\adios2\scripts\appveyor\appveyor_ninja.cmake
    -Ddashboard_full=OFF
    -Ddashboard_do_test=true
    -DCTEST_BUILD_NAME=%CUSTOM_BUILD_NAME%

# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
