#------------------------------------------------------------------------------#
# Distributed under the OSI-approved Apache License, Version 2.0.  See
# accompanying file Copyright.txt for details.
#------------------------------------------------------------------------------#

set(CTEST_PROJECT_NAME "ADIOS")
set(CTEST_NIGHTLY_START_TIME "01:00:00 UTC")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "open.cdash.org")
set(CTEST_DROP_LOCATION "/submit.php?project=ADIOS")
set(CTEST_DROP_SITE_CDASH TRUE)
set(MEMORYCHECK_SUPPRESSIONS_FILE ${CMAKE_SOURCE_DIR}/scripts/dashboard/nightly/valgrind-suppressions.txt)

# Ignore tests that are currently failing, remove tests here as they are fixed
list(APPEND CTEST_CUSTOM_MEMCHECK_IGNORE
  Bindings.C.ADIOS2_C_API.ADIOS2BPWriteTypes.Serial
  Bindings.C.BPWriteReadMultiblockCC.ZeroSizeBlocks.Serial
  Engine.BP.*/BPAppendAfterStepsP.Test/*.BP5.Serial
  Engine.BP.*/BPChangingShapeWithinStep.MultiBlock/*.BP5.Serial
  Engine.BP.*/BPParameterSelectStepsP.Read/*.BP5.Serial
  Engine.BP.*/BPReadMultithreadedTestP.ReadFile/*.BP5.Serial
  Engine.BP.*/BPStepsFileGlobalArrayParameters.EveryOtherStep/*.BP5.Serial
  Engine.BP.*/BPStepsFileGlobalArrayReaders.EveryStep/*.BP5.Serial
  Engine.BP.*/BPStepsFileGlobalArrayReaders.NewVarPerStep/*.BP5.Serial
  Engine.BP.*/BPStepsFileLocalArrayParameters.EveryOtherStep/*.BP5.Serial
  Engine.BP.*/BPStepsFileLocalArrayReaders.EveryStep/*.BP5.Serial
  Engine.BP.*/BPStepsFileLocalArrayReaders.NewVarPerStep/*.BP5.Serial
  Engine.BP.BPChangingShape.BPWriteReadShape2D.BP5.Serial
  Engine.BP.BPLargeMetadata.ManyLongStrings.BP5.Serial
  Engine.BP.BPWriteAppendReadTestADIOS2.ADIOS2BPWriteAppendRead2D2x4.BP5.Serial
  Engine.BP.BPWriteAppendReadTestADIOS2.ADIOS2BPWriteAppendReadAggregate.BP5.Serial
  Engine.BP.BPWriteAppendReadTestADIOS2.ADIOS2BPWriteAppendReadVaryingAggregation.BP5.Serial
  Engine.BP.BPWriteMultiblockReadTest.ADIOS2BPWriteMultiblockRead1D8.BP5.Serial
  Engine.BP.BPWriteMultiblockReadTest.ADIOS2BPWriteMultiblockRead2D2x4.BP5.Serial
  Engine.BP.BPWriteMultiblockReadTest.ADIOS2BPWriteMultiblockRead2D4x2.BP5.Serial
  Engine.BP.BPWriteMultiblockReadTest.ADIOS2BPWriteRead1D8ZeroBlock.BP5.Serial
  Engine.BP.BPWriteReadAsStreamTestADIOS2.ReaderWriterDefineVariable.BP5.Serial
  Engine.BP.BPWriteReadAttributes.BPWriteReadSingleTypesVar.BP5.Serial
  Engine.BP.BPWriteReadAttributes.WriteReadArrayTypes.BP5.Serial
  Engine.BP.BPWriteReadAttributes.WriteReadArrayTypesVar.BP5.Serial
  Engine.BP.BPWriteReadAttributes.WriteReadSingleTypes.BP5.Serial
  Engine.BP.BPWriteReadAttributes.WriteReadStreamVarp.BP5.Serial
  Engine.BP.BPWriteReadAttributeTestMultirank.ADIOS2BPWriteReadArrayTypes.BP5.Serial
  Engine.BP.BPWriteReadBlockInfo.BPWriteReadBlockInfo1D8_C.BP3.Serial
  Engine.BP.BPWriteReadBlockInfo.BPWriteReadBlockInfo1D8_C.BP4.Serial
  Engine.BP.BPWriteReadBlockInfo.BPWriteReadBlockInfo1D8_C.BP5.Serial
  Engine.BP.BPWriteReadBlockInfo.BPWriteReadBlockInfo1D8.BP5.Serial
  Engine.BP.BPWriteReadBlockInfo.BPWriteReadBlockInfo2D2x4.BP5.Serial
  Engine.BP.BPWriteReadLocalVariables.ADIOS2BPWriteReadLocal1DAllSteps.BP5.Serial
  Engine.BP.BPWriteReadLocalVariables.ADIOS2BPWriteReadLocal1DBlockInfo.BP5.Serial
  Engine.BP.BPWriteReadLocalVariables.ADIOS2BPWriteReadLocal2DChangeCount.BP3.Serial
  Engine.BP.BPWriteReadLocalVariables.ADIOS2BPWriteReadLocal2DChangeCount.BP4.Serial
  Engine.BP.BPWriteReadLocalVariables.ADIOS2BPWriteReadLocal2DChangeCount.BP5.Serial
  Engine.BP.BPWriteReadLocalVariablesSel.BPWriteReadLocal1DAllStepsSel.BP5.Serial
  Engine.BP.BPWriteReadLocalVariablesSelHighLevel.BPWriteReadLocal1DAllStepsSel.BP5.Serial
  Engine.BP.BPWriteReadMultiblockTest.ADIOS2BPWriteReadMultiblock1D8.BP5.Serial
  Engine.BP.BPWriteReadMultiblockTest.ADIOS2BPWriteReadMultiblock2D2x4.BP5.Serial
  Engine.BP.BPWriteReadMultiblockTest.ADIOS2BPWriteReadMultiblock2D4x2.BP5.Serial
  Engine.BP.BPWriteReadMultiblockTest.MultiblockNullBlocks.BP5.Serial
  Engine.BP.BPWriteReadMultiblockTest.MultiblockPerformDataWrite.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead10D2x2.Async.BP5.EWS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead10D2x2.Async.BP5.EWS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead10D2x2.Async.BP5.TLS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead10D2x2.Async.BP5.TLS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead10D2x2.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead1D8.Async.BP5.EWS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead1D8.Async.BP5.EWS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead1D8.Async.BP5.TLS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead1D8.Async.BP5.TLS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead1D8.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D2x4.Async.BP5.EWS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D2x4.Async.BP5.EWS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D2x4.Async.BP5.TLS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D2x4.Async.BP5.TLS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D2x4.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2_MultiStepsOverflow.Async.BP5.EWS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2_MultiStepsOverflow.Async.BP5.EWS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2_MultiStepsOverflow.Async.BP5.TLS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2_MultiStepsOverflow.Async.BP5.TLS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2_MultiStepsOverflow.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2_ReadMultiSteps.Async.BP5.EWS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2_ReadMultiSteps.Async.BP5.EWS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2_ReadMultiSteps.Async.BP5.TLS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2_ReadMultiSteps.Async.BP5.TLS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2_ReadMultiSteps.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2.Async.BP5.EWS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2.Async.BP5.EWS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2.Async.BP5.TLS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2.Async.BP5.TLS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ADIOS2BPWriteRead2D4x2.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2.GetDeferredInClose.Async.BP5.EWS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.GetDeferredInClose.Async.BP5.EWS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.GetDeferredInClose.Async.BP5.TLS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.GetDeferredInClose.Async.BP5.TLS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.GetDeferredInClose.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2.ReadStartCount.Async.BP5.EWS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ReadStartCount.Async.BP5.EWS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ReadStartCount.Async.BP5.TLS.Guided.Serial
  Engine.BP.BPWriteReadTestADIOS2.ReadStartCount.Async.BP5.TLS.Naive.Serial
  Engine.BP.BPWriteReadTestADIOS2.ReadStartCount.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2fstream.ADIOS2BPWriteRead1D8.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2fstream.ADIOS2BPWriteRead2D2x4.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2fstream.ADIOS2BPWriteRead2D4x2_MultiStepsOverflow.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2fstream.ADIOS2BPWriteRead2D4x2_ReadMultiSteps.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2fstream.ADIOS2BPWriteRead2D4x2.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2stdio.ADIOS2BPWriteRead1D8.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2stdio.ADIOS2BPWriteRead2D2x4.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2stdio.ADIOS2BPWriteRead2D4x2_MultiStepsOverflow.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2stdio.ADIOS2BPWriteRead2D4x2_ReadMultiSteps.BP5.Serial
  Engine.BP.BPWriteReadTestADIOS2stdio.ADIOS2BPWriteRead2D4x2.BP5.Serial
  Engine.BP.BPWriteReadVector.ADIOS2BPWriteRead1D8.BP5.Serial
  Engine.BP.BPWriteReadVector.ADIOS2BPWriteRead2D2x4.BP5.Serial
  Engine.BP.BPWriteReadVector.ADIOS2BPWriteRead2D4x2.BP5.Serial
  Engine.BP.BPWriteReadVector.ADIOS2BPWriteReadVector2D4x2_MultiSteps.BP5.Serial
  Engine.BPEngineTest.ZfpComplex.Serial
  Engine.SST.SstWriteFails.InvalidBeginStep.Serial
  Engine.SST.SstWriteFails.InvalidPut.Serial
  Engine.Staging.TestThreads.Basic.SST.BP.Serial
  Engine.Staging.TestThreads.Basic.SST.FFS.Serial
  Interface.ADIOS2_CXX11_API_Selection.MemorySelectionComplex.BPfile.Serial
  Interface.ADIOS2_CXX11_API_Selection.MemorySelectionReadStart.BPfile.Serial
  Remote.BPWriteMemorySelectionRead.FileRemote
  Remote.BPWriteMemorySelectionRead.GetRemote
  Remote.BPWriteReadADIOS2stdio.GetRemote
  remoteServerCleanup
  remoteServerSetup
  Staging.1x1.Attrs.BP5
  Staging.1x1.Attrs.CommMin.BP.SST
  Staging.1x1.Attrs.CommMin.BP5.SST
  Staging.1x1.CommMin.BP.SST
  Staging.1x1.CommMin.BP5.SST
  Staging.1x1.ForcePreload.CommMin.BP.SST
  Staging.1x1.ForcePreload.CommMin.BP5.SST
  Staging.1x1.Local2.CommMin.BP.SST
  Staging.1x1.Local2.CommMin.BP5.SST
  Staging.1x1.LocalMultiblock.CommMin.BP.SST
  Staging.1x1.LocalMultiblock.CommMin.BP5.SST
  Staging.1x1.ModAttrs.BP5
  Staging.1x1.ModAttrs.CommMin.BP.SST
  Staging.1x1.ModAttrs.CommMin.BP5.SST
  Staging.1x1.NoPreload.CommMin.BP.SST
  Staging.1x1.NoPreload.CommMin.BP5.SST
  Staging.1x1.SstRUDP.CommMin.BP.SST
  Staging.1x1.SstRUDP.CommMin.BP5.SST
  Staging.1x1Joined.BP5
  Staging.1x1Joined.CommMin.BP5.SST
  Staging.1x1LockGeometry.CommMin.BP.SST
  Staging.1x1LockGeometry.CommMin.BP5.SST
  Staging.1x1Struct.BP5
  Staging.1x1Struct.CommMin.BP5.SST
  Staging.1x1VarDestruction.CommMin.BP.SST
  Staging.1x1VarDestruction.CommMin.BP5.SST
  Staging.AllToAllDistribution.1x1x3.CommMin.BP.SST
  Staging.AllToAllDistribution.1x1x3.CommMin.BP5.SST
  Staging.DiscardWriter.1x1.CommMin.BP.SST
  Staging.DiscardWriter.1x1.CommMin.BP5.SST
  Staging.LatestReader.1x1.CommMin.BP.SST
  Staging.LatestReader.1x1.CommMin.BP5.SST
  Staging.LatestReaderHold.1x1.CommMin.BP.SST
  Staging.LatestReaderHold.1x1.CommMin.BP5.SST
  Staging.OnDemandSingle.1x1.CommMin.BP.SST
  Staging.OnDemandSingle.1x1.CommMin.BP5.SST
  Staging.RoundRobinDistribution.1x1x3.CommMin.BP.SST
  Staging.RoundRobinDistribution.1x1x3.CommMin.BP5.SST
  Staging.TimeoutReader.1x1.CommMin.BP.SST
  Staging.TimeoutReader.1x1.CommMin.BP5.SST
  Staging.WriteMemorySelectionRead.1x1.CommMin.BP.SST
  Staging.WriteMemorySelectionRead.1x1.CommMin.BP5.SST
  Staging.ZFPCompression.1x1.CommMin.BP.SST
  Staging.ZFPCompression.1x1.CommMin.BP5.SST
  Staging.ZFPCompression.3x5.CommMin.BP.SST
  Staging.ZFPCompression.3x5.CommMin.BP5.SST
  Utils.ChangingShape.AlternatingStepsAndChangingShapeVar.Dump
  Utils.ChangingShape.AlternatingStepsVarSelection.Dump
  Utils.ChangingShape.ChangingShapeVarOneStep.Dump
  Utils.ChangingShape.Dump
  Utils.ChangingShape.FixedShapeVarTooManySteps.Dump
  Utils.ChangingShape.Screen
  Utils.CWriter
  Utils.CWriter.Bpls.Al.Dump
  Utils.CWriter.Bpls.h.Dump
  Utils.CWriter.Bpls.la.Dump
  Utils.CWriter.Bpls.la.Screen
  Utils.CWriter.Bpls.ldDav.Dump
  Utils.CWriter.Bpls.ldDavvv.Dump
  Utils.CWriter.Bpls.ldvarI16.Dump
)
