#!/bin/bash
mkdir build
cd build

export CMAKE_PREFIX_PATH="${PREFIX}:${CMAKE_PREFIX_PATH}"

cmake -LAH .. \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  -DCMAKE_BUILD_TYPE=Release \
  -DBUILD_SHARED_LIBS=ON \
  -DADIOS2_BUILD_EXAMPLES=OFF \
  -DADIOS2_BUILD_TESTING=OFF \
  -DADIOS2_USE_PYTHON=ON \
  -DPYTHON_EXECUTABLE=$PYTHON \
  -DADIOS2_USE_MPI=ON


make -j$CPU_COUNT && make install
