stages:
  - pre-job-status
  - init
  - build
  - test
  - cleanup
  - post-job-status

##########
# GitHub status plumbing
##########
.gh-status:
  tags: [nobatch]
  variables:
    GH_CTX: olcf/${CI_BUILD_LABEL}
  only:
   - /^github/pr[0-9][0-9]*_.*/
  script:
    - bash scripts/ci/scripts/github-post-status.sh 
        -t "${STATUS_ROBOT_KEY}" 
        -r ornladios/adios2 
        -c ${CI_COMMIT_SHA}
        -s ${GH_STATE} 
        -d "${GH_DESC}" 
        -x "${GH_CTX}"
        -u "${CI_PIPELINE_URL}"

.pre-status:
  extends:
    - .gh-status
  stage: pre-job-status
  variables:
    GH_STATE: pending
    GH_DESC: Running

.post-status-pass:
  extends:
    - .gh-status
  stage: post-job-status
  when: on_success
  variables:
    GH_STATE: success
    GH_DESC: Succeeded

.post-status-fail:
  extends:
    - .gh-status
  stage: post-job-status
  when: on_failure
  variables:
    GH_STATE: failure
    GH_DESC: Failed

################################################################################
# Job templates
################################################################################

.base:
  variables:
    GITLAB_SITE: "OLCF GitLab"
    EXTERNAL_WORKDIR: /gpfs/wolf/proj-shared/csc303/ci/${CI_PIPELINE_ID}_${CI_BUILD_LABEL}
  before_script:
    - module load cmake git
    - mkdir -pv ${EXTERNAL_WORKDIR}/source
    - cd ${EXTERNAL_WORKDIR}/source

# Use a work directory on the shared filesystem accessible to compute nodes
.init-step:
  extends:
    - .base
  stage: init
  tags: [nobatch]
  script:
    - cd ..
    - rm -rfv source
    - git clone -b ${CI_COMMIT_BRANCH} ${CI_REPOSITORY_URL} --depth=1 source

.build-step:
  extends:
    - .base
  stage: build
  tags: [nobatch]
  script:
    - bash scripts/ci/gitlab-ci/run.sh update
    - bash scripts/ci/gitlab-ci/run.sh configure
    - bash scripts/ci/gitlab-ci/run.sh build

.test-step:
  extends:
    - .base
  stage: test
  script:
    - bash scripts/ci/gitlab-ci/run.sh test end

.cleanup-step:
  extends:
    - .base
  stage: cleanup
  tags: [nobatch]
  script:
    - cd ${CI_PROJECT_DIR}
    - rm -rf ${EXTERNAL_WORKDIR}

################################################################################
# XL + SMPI
################################################################################
.ascent-xl-smpi:
  variables:
    CI_BUILD_LABEL: ascent-xl-smpi

ascent-xl-smpi-pre:
  extends:
    - .ascent-xl-smpi
    - .pre-status

ascent-xl-smpi-init:
  extends:
    - .ascent-xl-smpi
    - .init-step

ascent-xl-smpi-build:
  extends:
    - .ascent-xl-smpi
    - .build-step

ascent-xl-smpi-test:
  extends:
    - .ascent-xl-smpi
    - .test-step
  tags: [batch]
  variables:
    LD_PRELOAD: /usr/lib64/libibverbs.so.1 /usr/lib64/librdmacm.so.1
    SCHEDULER_PARAMETERS: "-P CSC303 -W 1:00 -nnodes 2"

ascent-xl-smpi-post-pass:
  extends:
    - .ascent-xl-smpi
    - .post-status-pass

ascent-xl-smpi-post-fail:
  extends:
    - .ascent-xl-smpi
    - .post-status-fail

ascent-xl-smpi-cleanup:
  extends:
    - .ascent-xl-smpi
    - .cleanup-step
