#  This file is used to define the GitLab CI/CD pipeline for the ADIOS2 project.
default:
  interruptible: true
  tags:
    - hpsf-gpu
    - linux-5.15

#  This file is used to define the GitLab CI/CD pipeline for the ADIOS2 project.
.common:
  image:
    name: ubuntu
    pull_policy: always
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success
    - when: never
  variables:
    GITLAB_SITE: "UO CI (gitlab.spack.io)"
    CI_BIN_DIR:  "$CI_PROJECT_DIR/build"

.common-build:
  extends:
    - .common
  stage: build
  script:
    - bash scripts/ci/gitlab-ci/run.sh update
    - bash scripts/ci/gitlab-ci/run.sh configure
    - bash scripts/ci/gitlab-ci/run.sh build
  artifacts:
    expire_in: 1 hours
    when: always
    paths:
      - $CI_BIN_DIR/
    exclude:
      - $CI_BIN_DIR/**/*.o

.common-test:
  extends:
    - .common
  stage: test
  script:
    - bash scripts/ci/gitlab-ci/run.sh test

.common-memcheck:
  extends:
    - .common
  stage: test
  script:
    - bash scripts/ci/gitlab-ci/run.sh memcheck

#===============================================================================
build:uo-ubuntu22.04-gcc11:
  image:
    name: ghcr.io/ornladios/adios2:ci-spack-ubuntu22.04-gcc11
    entrypoint: [""]
  before_script:
    - source /spack/share/spack/setup-env.sh
  extends: [.common-build]

test:uo-ubuntu22.04-gcc11:
  image:
    name: ghcr.io/ornladios/adios2:ci-spack-ubuntu22.04-gcc11
    entrypoint: [""]
  before_script:
    - source /spack/share/spack/setup-env.sh
  extends: [.common-test]
  needs: [build:uo-ubuntu22.04-gcc11]

#===============================================================================
build:uo-sanitizer-asan:
  image:
    name: ghcr.io/ornladios/adios2:ci-opensuse-tw-asan-20241205
  extends: [.common-build]

build:uo-sanitizer-msan:
  image:
    name: ghcr.io/ornladios/adios2:ci-opensuse-tw-msan-20241205
  extends: [.common-build]

build:uo-sanitizer-tsan:
  image:
    name: ghcr.io/ornladios/adios2:ci-opensuse-tw-tsan-20241205
  extends: [.common-build]

build:uo-sanitizer-ubsan:
  image:
    name: ghcr.io/ornladios/adios2:ci-opensuse-tw-ubsan-20241205
  extends: [.common-build]

test:uo-sanitizer-asan:
  image:
    name: ghcr.io/ornladios/adios2:ci-opensuse-tw-asan-20241205
  extends: [.common-memcheck]
  needs: [build:uo-sanitizer-asan]

test:uo-sanitizer-msan:
  image:
    name: ghcr.io/ornladios/adios2:ci-opensuse-tw-msan-20241205
  extends: [.common-memcheck]
  needs: [build:uo-sanitizer-msan]

test:uo-sanitizer-tsan:
  image:
    name: ghcr.io/ornladios/adios2:ci-opensuse-tw-tsan-20241205
  extends: [.common-memcheck]
  needs: [build:uo-sanitizer-tsan]

test:uo-sanitizer-ubsan:
  image:
    name: ghcr.io/ornladios/adios2:ci-opensuse-tw-ubsan-20241205
  extends: [.common-memcheck]
  needs: [build:uo-sanitizer-ubsan]

deploy:sync-ornl:
  environment: ornl
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
    - when: never
  image:
    name: ornladios/adios2:sync-20241206-b
    pull_policy: always
  script: >
    .gitlab/config/SpackCIBridge.py
    ornladios/ADIOS2
    git@code.ornl.gov:ecpcitest/adios2.git
    https://code.ornl.gov/
    ecpcitest/adios2
    --prereq-check=format
    --prereq-check=git_checks
    --disable-status-post
  dependencies: []
  needs: []

deploy:sync-spack:
  environment: spackio
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: on_success
    - when: never
  image:
    name: ornladios/adios2:sync-20241206-b
    pull_policy: always
  script: >
    .gitlab/config/SpackCIBridge.py
    ornladios/ADIOS2
    git@ssh.gitlab.spack.io:adios2/adios2.git
    https://gitlab.spack.io/
    adios2/ADIOS2
    --prereq-check=format
    --prereq-check=git_checks
    --status-context="Frank CI (sanitizers)"
  dependencies: []
  needs: []
