# SPDX-FileCopyrightText: 2026 Oak Ridge National Laboratory and Contributors
#
# SPDX-License-Identifier: Apache-2.0

---
# adios2 config file in yaml format
- IO: "TestIO"
    
  Variables:
    
  - Variable: "r32"
    Operations:
    # throw an exception since type is not a keyword, but Type
    - { type: zfp, rate: 8 }
