#!/bin/bash
#BSUB -P CSC143SUMMITDEV
#BSUB -W 30
#BSUB -nnodes 2
#BSUB -o adios2_nightly.%I.out
#BSUB -e adios2_nightly.%I.err

case ${LSB_JOBINDEX} in
  1) CTEST_COMPILER=gcc
     ;;
  2) CTEST_COMPILER=xl
     ;;
  3) CTEST_COMPILER=pgi
     ;;
  *) echo "Error: Unsupported LSB_JOBINDEX: ${LSB_JOBINDEX}"
     exit
     ;;
esac

echo "LSB_JOBINDEX: ${LSB_JOBINDEX}"
echo "CTEST_COMPILER: ${CTEST_COMPILER}"

module purge
module load git cmake

CTEST=$(which ctest)
SCRIPT_DIR=${PWD}/source/scripts/dashboard/nightly
${CTEST} -VV -S ${SCRIPT_DIR}/summitdev-${CTEST_COMPILER}-spectrum.cmake \
  -Ddashboard_full=OFF \
  -Ddashboard_do_test=ON \
  -Ddashboard_do_submit=OFF 2>&1 1>>summitdev-${CTEST_COMPILER}-spectrum.log
