# SPDX-FileCopyrightText: 2026 Oak Ridge National Laboratory and Contributors
#
# SPDX-License-Identifier: Apache-2.0

ARG BASE_IMAGE=ghcr.io/ornladios/adios2:ci-spack-ubuntu22.04-base
FROM $BASE_IMAGE
ARG CLANG_VERSION=11

RUN apt-get update && apt-get install -y \
    clang-${CLANG_VERSION} \
    libomp-dev && \
    rm -rf /var/lib/apt/lists/*
