#!/usr/bin/env bash

echo "Setting up git aliases..."
if ! which clang-format 2>1 1>/dev/null
then
  echo "ADIOS development requires clang-format to be available in your path."
  exit 1
fi

if ! git config alias.clang-format "!scripts/developer/git/git-clang-format"
then
  echo "Error adding clang-format alias"
  exit 2
fi

exit 0
