#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Oak Ridge National Laboratory and Contributors
#
# SPDX-License-Identifier: Apache-2.0

echo "Setting up git aliases..."
if ! which clang-format 1>/dev/null 2>&1
then
  echo "Warning: ADIOS uses clang-format to enforce style guidelines but no"
  echo "         clang-format binary was found in your path"
fi

if ! git config alias.clang-format "!scripts/developer/git/git-clang-format"
then
  echo "Waring: Error adding clang-format alias"
fi

exit 0
