# SPDX-FileCopyrightText: 2026 Oak Ridge National Laboratory and Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: external
on:
  push:
  pull_request_target:

permissions:
  contents: read

jobs:
  generate_statuses:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
      - uses: Kitware/cdash-status@697751fc655b300a9e16e285f2e2ee981f59e45a # release
        with:
          project: ADIOS
