name: Python Packaging

on:
  workflow_dispatch:
    inputs:
      overrideVersion:
        description: Manually force a version
      pypiServer:
        description: Server to publish the pip package
        required: true
        default: 'testpypi'
        type: choice
        options:
          - 'testpypi'
          - 'pypi'

  pull_request:
  push:
    branches:
      - master
      - release_[0-9]+
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  release:
    types:
      - published

permissions:
  contents: read

env:
  ADIOS2_CUSTOM_VERSION_OVERRIDE: ${{ github.event.inputs.overrideVersion }}

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write  # for upload-artifact
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 0

      - name: Generate common version file
        run: cmake -P scripts/ci/gh-actions/config/adios-version.cmake && echo VERSION.TXT

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v4
        with:
          name: artifact_sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      actions: write  # for upload-artifact
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4
        with:
          fetch-depth: 0

      - name: Generate common version file
        run: cmake -P scripts/ci/gh-actions/config/adios-version.cmake && echo VERSION.TXT

      - uses: pypa/cibuildwheel@9c00cb4f6b517705a3794b22395aedc36257242c # v2.16
        env:
          CIBW_BUILD: cp*-manylinux_x86_64

      - name: Upload wheels
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v4
        with:
          name: artifact_wheels
          path: wheelhouse/*.whl

  upload_pypi:
    needs: [build_wheels, make_sdist]
    environment: pypi
    permissions:
      contents: read
      actions: read  # for download-artifact
      id-token: write
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' && github.event.inputs.pypiServer == 'pypi' ||
      (
        github.event_name == 'release' &&
        github.event.action == 'published'
      )
    steps:
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1

  upload_test_pypi:
    needs: [build_wheels, make_sdist]
    environment: testpypi
    permissions:
      contents: read
      actions: read  # for download-artifact
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.pypiServer == 'testpypi'
    steps:
      - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v4
        with:
          path: dist
          merge-multiple: true
      - run: ls -R dist
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # v1
        with:
          repository-url: https://test.pypi.org/legacy/
