# SPDX-FileCopyrightText: Oak Ridge National Laboratory and Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: REUSE Compliance

on:
  push:
    branches:
      - master
      - 'release*'
  pull_request:
    branches:
      - master
      - 'release*'
permissions:
  contents: read

jobs:
  reuse:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check REUSE compliance
        run: pipx run reuse lint
