# SPDX-FileCopyrightText: Oak Ridge National Laboratory and Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: REUSE Compliance

on:
  push:
    branches:
      - master
      - 'release*'
  pull_request:
    branches:
      - master
      - 'release*'
permissions:
  contents: read

jobs:
  reuse:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Check REUSE compliance
        run: pipx run reuse lint
