# SPDX-FileCopyrightText: Oak Ridge National Laboratory and Contributors
#
# SPDX-License-Identifier: Apache-2.0

name: SBOM

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Generate SPDX SBOM
        run: pipx run reuse spdx -o adios2-sbom.spdx

      - name: Upload SBOM to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.event.release.tag_name }} adios2-sbom.spdx
