name: OLCF sync script

on:
  schedule:
    - cron: "0/10 * * * *"
  workflow_dispatch:

jobs:
  sync-script:
    if: github.repository == 'ornladios/ADIOS2'
    name: Sync Script
    runs-on: ubuntu-20.04
    environment: sync-script
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.6.15'
      - run: pip install python-dateutil PyGithub
      - run: >
          .gitlab/config/SpackCIBridge.py
          ornladios/ADIOS2 git@code.ornl.gov:ecpcitest/adios2.git
          https://code.ornl.gov/ ecpcitest/adios2
          --prereq-check=format --prereq-check=git_checks --disable-status-post
        env:
          GITLAB_SSH_KEY_BASE64: ${{ secrets.GITLAB_SSH_KEY_BASE64}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

