name: Triggers

on:
  workflow_run:
    workflows: ["Build and Test"]
    types: [requested]

jobs:
  all_triggers:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Post CDash Status
      run: scripts/ci/scripts/post-cdash-status.sh ${{ github.event.repository.full_name }} ${{ github.event.workflow_run.head_sha }} ${{ secrets.GITHUB_TOKEN }}
